import { TitleBar } from "components/titlebar.slint";
import { LowBar } from "components/lowbar.slint";
import { ContentArea } from "components/content_area.slint";
import { BackgroundSelector, BackgroundItem } from "components/backgrounds.slint";
import { AppPage, AppState } from "globals.slint";
export { SettingsState } from "globals.slint";

export component AppWindow inherits Window {
    callback window-drag();

    callback close-clicked();
    callback minimize-clicked();
    callback play-clicked();

    callback search-clicked();
    callback home-clicked();
    callback settings-clicked();
    
    callback open-discord();
    callback open-telegram();

    callback open-change-path();

    callback background-selected(string);

    in-out property <string> online-count: "—";
    in-out property <string> version: "1.0.0";
    in-out property <string> update-date: "21.05.2026";

    in-out property <string> telegram-link: "https://telegram.com";
    in-out property <string> discord-link: "https://discord.com";
    in-out property <string> game-path: "";

    in-out property <bool> use-background-image: false;
    in property <image> background-image;

    in-out property <[BackgroundItem]> backgrounds;
    in-out property <string> selected-background-name: "";

    width: 540px;
    height: 540px;

    title: "DBDLegacy";
    icon: @image-url("../img/icon.png");
    no-frame: true;
    background: transparent;

    Rectangle {
        x: 0px;
        y: 0px;
        width: root.width;
        height: root.height;

        border-radius: 24px;
        clip: true;

        background: #131115;

        Image {
            width: root.width;
            height: root.height;

            source: root.background-image;
            opacity: 25%;
            visible: root.use-background-image;
            image-fit: cover;
        }

        drag := TouchArea {
            x: 0px;
            y: 0px;

            width: parent.width;
            height: 62px;

            moved => {
                root.window-drag();
            }
        }

        TitleBar {
            x: 194px;
            y: 0px;

            width: parent.width - self.x;
            height: 62px;

            close-clicked => {
                root.close-clicked();
            }

            minimize-clicked => {
                root.minimize-clicked();
            }

            home-clicked => {
                root.home-clicked();
            }

            search-clicked => {
                root.search-clicked();
            }

            settings-clicked => {
                root.settings-clicked();
            }
        }

        Rectangle {
            x: 0px;
            y: 57px;

            width: parent.width;
            height: 428px;
            
            background: transparent;

            ContentArea {
                width: parent.width;
                height: parent.height;

                online-count: root.online-count;
                update-date: root.update-date;
                version: root.version;
                game-path: root.game-path;

                backgrounds: root.backgrounds;
                selected-background-name: root.selected-background-name;

                play-clicked => {
                    root.play-clicked();
                }

                open-change-path => {
                    root.open-change-path();
                }

                background-selected(name) => {
                    root.selected-background-name = name;
                    root.background-selected(name);
                }
            }
        }

        LowBar {
            x: 0px;
            y: 485px;
            width: parent.width;
            height: 44px;

            open-discord => {
                root.open-discord();
            }

            open-telegram => {
                root.open-telegram();
            }
        }
    }

    home-clicked => {
        AppState.current-page = AppPage.Main;
    }

    settings-clicked => {
        AppState.current-page = AppPage.Settings;
    }

    search-clicked => {
        AppState.current-page = AppPage.Search;
    }
}
